version: '3.4'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
        - ./backend:/home/app/backend
    ports:
      - 8000:8000
